FROM python:3.11-slim
RUN pip install poetry

WORKDIR /app
ENV POETRY_VIRTUALENVS_CREATE=TRUE
ENV POETRY_VIRTUALENVS_IN_PROJECT=TRUE

COPY poetry.lock poetry.lock
COPY pyproject.toml pyproject.toml

RUN poetry install

COPY static static
COPY templates templates
COPY main.py main.py

CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
