FROM prefecthq/prefect:2.19.5-python3.10

COPY prefect data-platform-flows

RUN prefect work-pool create --type process light-work-pool

RUN prefect deploy data-platform-flows/example_flow.py:register_file_flow \
    -n register_file \ 
    -p light-work-pool

CMD ["prefect", "server", "start", "--host", "0.0.0.0"]
