FROM python:3.11-slim

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock

ENV POETRY_VIRTUALENVS_CREATE=TRUE
ENV POETRY_VIRTUALENVS_IN_PROJECT=TRUE

RUN poetry install --only main,backend

COPY backend backend
COPY __init__.py __init__.py

ENV DATABASE_URL=$DATABASE_URL

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "5000"]