FROM python:3.11-slim

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock

ENV POETRY_VIRTUALENVS_CREATE=TRUE
ENV POETRY_VIRTUALENVS_IN_PROJECT=TRUE

RUN poetry install --only main,frontend

COPY frontend frontend
COPY __init__.py __init__.py

CMD ["bokeh", "serve", "frontend/main.py", "--allow-websocket-origin=*", "--prefix=/frontend", "--port", "8050"]
