services:
  frontend:
    build: ./frontend
    networks:
      - backend-network
    ports:
      - "8050:8050"

  backend:
    build: ./backend
    networks:
      - backend-network

networks:
  backend-network:
    driver: "bridge"
